[Settings]
ID = "cybno"

# Redirect all paths that don't match to our storage at the
# webserver maintained by the Department of Informatics
[[redirects]]
  from = "/*"
  to = "https://heim.ifi.uio.no/~cyb/:splat"

  status = 200

