[Settings]
ID = "cybno"

# Redirect all paths that don't match to our storage at the
# webserver maintained by the Department of Informatics
[[redirects]]
  from = "/*"
  to = "https://heim.ifi.uio.no/~cyb/:splat"
  status = 200

# Redirect for our bylaws
[[redirects]]
  from = "https://vedtekter.cyb.no"
  to  = "https://cybernetisk.github.io/docs/vedtekter/vedtekter.pdf"
	status = 200

[[redirects]]
  from = "http://vedtekter.cyb.no"
  to  = "https://cybernetisk.github.io/docs/vedtekter/vedtekter.pdf"
	status = 200

